
def commands():
    print("0  -> Quit the program")
    print("1  -> Add a vector to the repository")
    print("2  -> Get all vectors ")
    print("3  -> Get vector at index")
    print("4  -> Update a vector at a given index")
    print("5  -> Update a vector identified by name_id")
    print("6  -> Delete vector by index")
    print("7  -> Delete a vector by name_id")
    print("8  -> Plot all vectors in a chart based on the type and colour of each vector ")
    print("9  -> Get the list of vectors having a given sum of elements ")
    print("10 -> Delete all vectors that are between two given indexes  ")
    print("11 -> Update the color of a vector identified by id ")
    print("12 -> Add 4 data examples")
    print("13 -> Test functions")
