def commands():
    print("0  -> Quit program")
    print("1  -> Add a point to the repository")
    print("2  -> Get all points")
    print("3  -> Get a point at a given index ")
    print("4  -> Get all points of a given color")
    print("5  -> Get all points that are inside a given square")
    print("6  -> Get the minimum distance between two points")
    print("7  -> Update a point at a given index")
    print("8  -> Delete a point by index")
    print("9  -> Delete all points that are inside a given square")
    print("10 -> Plot all points in a chart")
    print("11 -> Shift all points on the x axis")
    print("12 -> Test functions")
    print("13 -> get 3 data examples")
    print("14 -> get 10 data examples")
