def commands():
    # UI function
    print("List of commands: ")
    print("0 -> Quit the program")
    print()
    print("Add the result of a new participant to the array")
    print("1 -> Add element")
    print("2 -> Insert element at index position")
    print()
    print("Modify the scores in the array ")
    print("3 -> Remove given index")
    print("4 -> Remove from index to index")
    print("5 -> Replaces the score on index with the given value")
    print()
    print("Get the participants with scores having some properties")
    print("6 -> Get participants with score less than the given value")
    print("7 -> Get participants sorted by their score")
    print("8 -> Get sorted participants with scores higher than the given value")
    print()
    print("Obtain different characteristics of participants")
    print("9 -> Get the average score for participants between the two given index")
    print("10 -> Get the minimum score for participants betweenthe two given index")
    print("11 -> Get the scores of participants between the two given values")
    print()
    print("Filter values")
    print("12 -> Keep the participants with scores multiple of the given value")
    print("13 -> Keep the participants with scores higher then the given value")
    print()
    print("Undo")
    print("14 -> Undo the last operation")
    print()
    print("15 -> Run tests for all functions")
